[[plugins]]
repo = 'Shougo/neomru.vim'
on_path = '.*'

[[plugins]]
repo = 'Shougo/unite.vim'
hook_source = '''
let g:unite_source_history_yank_enable = 1
try
  let g:unite_source_rec_async_command='ag --nocolor --nogroup -g ""'
  call unite#filters#matcher_default#use(['matcher_fuzzy'])
catch
endtry
" search a file in the filetree
nnoremap <space><space> :split<cr> :<C-u>Unite -start-insert file_rec/async
" reset not it is <C-l> normally
:nnoremap <space>r <Plug>(unite_restart)
:let g:vimfiler_as_default_explorer = 1
'''
depends = 'neomru.vim'

[[plugins]]
repo = 'Shougo/vimfiler'

# 行末スペース削除
[[plugins]]
repo = 'bronson/vim-trailing-whitespace'
hook_source = '''
let g:indent_guides_enable_on_vim_startup = 1
'''

# エディタ設定
# インデントに色を付けて見やすくする
[[plugins]]
repo = 'nathanaelkane/vim-indent-guides'
